### PR TITLE
Fix mission jump boundary conditions

### PR DESCRIPTION
**Pull request by stephengtuggy**
Some whitespace formatting changes are also included.

### CODE REVIEW

**Comment by stephengtuggy** [comment]
Should fix #4

**Comment by stephengtuggy** [comment]
Testing still pending.

**Comment by stephengtuggy** [comment]
This change has been tested in VS:UtCS, and it appears to be good. So I think I'll go ahead and mark this PR as ready.

**Review by ermo — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
